#
version: '3.6'

services:
  ipfs:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    image: asperitus/ipfs:latest
    container_name: ipfs
    environment:
      - HOST_USER=$USER
    volumes:
      - $HOME:/host
    restart: always